CRUDASP/Pages/Editar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using CRUDASP.Model;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CRUDASP.Pages
{
    public class EditarModel : PageModel
    {
         
        public List<Provincia> provincias = new List<Provincia>();
        public Persona personaBuscada = new Persona();
        private SqlConnection DB;
        public EditarModel() { 
        this.DB = new SqlConnection("Data Source=DESKTOP-V32QJTJ\\SQLEXPRESS;Initial Catalog=CRUD;Integrated Security=True");
      
        }
        public void OnGet(int Editar)
        {
            var parametros = new { @IdPersona=Editar };

            this.personaBuscada = this.DB.QueryFirst<Persona>("ObtenerPersonaPorId", parametros, commandType: CommandType.StoredProcedure);
            this.provincias = this.DB.Query<Provincia>("ObtenerProvincias", null, commandType: CommandType.StoredProcedure).ToList();
           
        }

        public ActionResult OnPostEditar(Persona persona) {
            var parametros = new { @IdPersona = persona.PersonAId,@nombre=persona.Nombre, @Apellido = persona.Apellido, @provincia=persona.IdProvincia };
            this.DB.Query("EditarPersona", parametros, commandType: CommandType.StoredProcedure);
            
            return RedirectToPage("Index");
        }
       
    }
}

CRUDASP/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CRUDASP.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CRUDASP/Pages/Index.cshtml.cs
using CRUDASP.Model;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace CRUDASP.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private SqlConnection DB;
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
            this.DB = new SqlConnection("Data Source=DESKTOP-V32QJTJ\\SQLEXPRESS;Initial Catalog=CRUD;Integrated Security=True");
        }


        public PersonaProvinciaDTO PersonasProvinciasDto = new PersonaProvinciaDTO();
        public void OnGet()
        {
            //cargamos la informacion de la base de datos
            List<Provincia> listaProvincias = this.DB.Query<Provincia>("ObtenerProvincias", null, commandType: CommandType.StoredProcedure).ToList();
            List<PersonaProvincia> listaPersonas = this.DB.Query<PersonaProvincia>("ObtenerPersonas", null, commandType: CommandType.StoredProcedure).ToList();

            this.PersonasProvinciasDto.Provincias =listaProvincias;
            this.PersonasProvinciasDto.Personas =listaPersonas;
           
        }


        public void OnPostAgregar(Persona persona) 
        {
            //Insertamos la nueva persona
            var parametros = new { @nombre=persona.Nombre, @apellido=persona.Apellido, @Idprovincia=persona.IdProvincia };
            this.DB.Query("InsertarPersona", parametros,commandType: CommandType.StoredProcedure);

            //cargamos la informacion de la base de datos
            List<Provincia> listaProvincias = this.DB.Query<Provincia>("ObtenerProvincias", null, commandType: CommandType.StoredProcedure).ToList();
            List<PersonaProvincia> listaPersonas = this.DB.Query<PersonaProvincia>("ObtenerPersonas", null, commandType: CommandType.StoredProcedure).ToList();

            this.PersonasProvinciasDto.Provincias = listaProvincias;
            this.PersonasProvinciasDto.Personas = listaPersonas;

        }

        public void OnPostEliminar(int Eliminar) {
            
            var parametros = new { @IdPersona=Eliminar };
            this.DB.Query("EliminarPersona", parametros, commandType: CommandType.StoredProcedure);

            //cargamos la informacion de la base de datos
            List<Provincia> listaProvincias = this.DB.Query<Provincia>("ObtenerProvincias", null, commandType: CommandType.StoredProcedure).ToList();
            List<PersonaProvincia> listaPersonas = this.DB.Query<PersonaProvincia>("ObtenerPersonas", null, commandType: CommandType.StoredProcedure).ToList();

            this.PersonasProvinciasDto.Provincias = listaProvincias;
            this.PersonasProvinciasDto.Personas = listaPersonas;
        }
    }
}

CRUDASP/Pages/Inicio.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CRUDASP.Pages
{
    public class InicioModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CRUDASP/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUDASP.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

CRUDASP/Pages/Editar.cshtml
@page
@model CRUDASP.Pages.EditarModel
@{
}
<br />
<h3>Edicion de registros</h3>
<form method="post" asp-page-handler="Editar">
    <input type="number" hidden value="@Model.personaBuscada.PersonAId" name="PersonAId"  />
    <div class="form-group">
        <label for="Nombre">Nombre</label>
        <input type="text" value="@Model.personaBuscada.Nombre" class="form-control" name="Nombre" id="Nombre"  placeholder="Nombre">
    </div>
    <div class="form-group">
        <label for="Apellido">Apellido</label>
        <input type="text" value="@Model.personaBuscada.Apellido" class="form-control" name="Apellido" id="Apellido" placeholder="Apellido">
    </div>
    <div class="form-group">
        <label for="Provincia">Provincia</label>
        <select id="Provincia" name="IdProvincia" class="form-control" >
            @foreach (var item in Model.provincias) { 
            <option value="@item.ProvinciaId">@item.NombreProvincia</option>
            }
            
        </select>
    </div>


    <button type="submit"  class="btn btn-info">Editar</button>
</form>
<form method="get" asp-page="Index">
    <button type="submit"  class="btn btn-danger">Cancelar</button>
</form>

CRUDASP/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<br />
<h3>Ventana principal</h3>
<form method="post" asp-page-handler="Agregar">
    <div class="form-group">
        <label for="nombre">Nombre</label>
        <input type="text" class="form-control" required name="Nombre" id="nombre" placeholder="Nombre">
    </div>
    <div class="form-group">
        <label for="apellido">Apellido</label>
        <input type="text" class="form-control" required name="Apellido" id="apellido" placeholder="Apellido">
    </div>
    <div class="form-group">
        <label for="provincia">Provincia</label>
        <select id="provincia" class="form-control" name="IdProvincia">
            @foreach (var item in Model.PersonasProvinciasDto.Provincias)
            {
                <option value="@item.ProvinciaId">@item.NombreProvincia</option>
            }
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
<br />
<hr />

<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Nombre</td>
            <td>Apellido</td>
            <td>Provincia</td>
            <td>Accion 1</td>
            <td>Accion 2</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.PersonasProvinciasDto.Personas)
        {
            <tr>
                <td>@item.PersonAId</td>
                <td>@item.Nombre</td>
                <td>@item.Apellido</td>
                <td>@item.NombreProvincia</td>
                <td>
                    <form method="post" asp-page-handler="Eliminar">
                        <button type="submit" name="Eliminar" value="@item.PersonAId" class="btn btn-danger">Eliminar</button>
                    </form>
                </td>
                <td>
                    <form method="get" asp-page="Editar">
                        <button type="submit" name="Editar" value="@item.PersonAId" class="btn btn-info">Editar</button>
                    </form>
                </td>

            </tr>
        }
    </tbody>

</table>

CRUDASP/Pages/Inicio.cshtml
@page
@model CRUDASP.Pages.InicioModel
@{
}

<h3>Inicio</h3>

CRUDASP/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CRUDASP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CRUDASP - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>